// next-enterprise/src/app/page.tsx
import {sanityFetch} from '@/sanity/fetch'
import './globals.css'
import {defineQuery} from 'groq'
import type {Metadata} from 'next'
import {Suspense} from 'react'
import {TimeSince} from './TimeSince'

const DEMO_QUERY = defineQuery(`*[_type == "demo" && slug.current == $slug][0].title`)
const slug = 'next-enterprise'

export async function generateMetadata(): Promise<Metadata> {
  const {data} = await sanityFetch({query: DEMO_QUERY, params: {slug}})
  return {
    title: data || 'Next Enterprise',
  }
}

export default async function Home() {
  const {data, fetchedAt} = await sanityFetch({query: DEMO_QUERY, params: {slug}})

  return (
    <div className="ring-theme relative mx-2 rounded-lg px-2 pb-1 pt-8 ring-1">
      <h1 className="min-w-64 text-balance text-4xl font-bold leading-tight tracking-tighter md:text-6xl lg:pr-8 lg:text-8xl">
        {data || 'Next Enterprise'}
      </h1>
      <Suspense>
        <TimeSince label="page.tsx" since={fetchedAt} />
      </Suspense>
    </div>
  )
}

// nuxt/app.vue
<script setup lang="ts">
import {sanityFetch} from '@/utils/sanity/fetch'
import {INDEX_QUERY} from '@/utils/sanity/queries'

const route = useRoute()

const {data: demo} = await useAsyncData(
  'index',
  () =>
    sanityFetch({
      query: INDEX_QUERY,
      params: {slug: 'nuxt'},
      lastLiveEventId: route.query.lastLiveEventId as string,
    }),
  {
    watch: [() => route.query.lastLiveEventId],
  },
)

useHead({
  title: demo.value?.data.title || 'Nuxt',
})
</script>

<template>
  <main
    class="bg-(--theme-background) text-(--theme-text) transition-colors duration-1000 ease-in-out"
    :style="{
      '--theme-background': demo?.data.theme?.background || undefined,
      '--theme-text': demo?.data.theme?.text || undefined,
    }"
  >
    <NuxtRouteAnnouncer />
    <div class="relative flex min-h-dvh flex-col items-center justify-evenly overflow-auto">
      <h1
        class="text-balance text-4xl font-bold leading-tight tracking-tighter md:text-6xl lg:pr-8 lg:text-8xl"
      >
        {{ demo?.data.title || 'Nuxt' }}
      </h1>
      <ThemeButton />
    </div>
    <ClientOnly>
      <SanityLive :tags="demo?.tags" />
    </ClientOnly>
  </main>
</template>
