// nuxt/app/components/SanityLive.vue
<script setup lang="ts">
/* eslint-disable vue/valid-template-root */
import {CorsOriginError} from '@sanity/client'
import {useRoute, useRouter} from '#app'
import {onMounted, onUnmounted} from 'vue'

const props = defineProps<{
  tags?: string[]
}>()

const router = useRouter()
const route = useRoute()
const liveEvents = useSanityLiveEvents()

let subscription: ReturnType<typeof liveEvents.subscribe> | null = null

onMounted(() => {
  subscription = liveEvents.subscribe({
    next: (event) => {
      if (event.type === 'welcome') {
        console.info('Sanity is live with automatic revalidation of published content')
        if (!route.query.lastLiveEventId) {
          router.replace({
            query: {
              ...route.query,
              lastLiveEventId:
                // @ts-expect-error - @TODO upgrade `@sanity/client` with the id of welcome events
                event.id,
            },
          })
        }
      }

      if (event.type === 'message') {
        if (event.tags.some((tag) => props.tags?.includes(tag))) {
          router.replace({query: {...route.query, lastLiveEventId: event.id}})
        }
      }

      if (event.type === 'reconnect' || event.type === 'restart') {
        const {lastLiveEventId, ...queryWithoutLastLiveEventId} = route.query
        router.replace({query: queryWithoutLastLiveEventId})
      }
    },
    error: (error) => {
      if (error instanceof CorsOriginError) {
        console.warn(
          `Sanity Live is unable to connect to the Sanity API as the current origin - ${window.origin} - is not in the list of allowed CORS origins for this Sanity Project.`,
          error.addOriginUrl && `Add it here:`,
          error.addOriginUrl?.toString(),
        )
      } else {
        console.error(error)
      }
    },
  })
})

onUnmounted(() => {
  subscription?.unsubscribe()
})
</script>

<template></template>

// sveltekit/src/lib/sanity/SanityLive.svelte
<script lang="ts">
  import {CorsOriginError} from '@sanity/client'
  import {goto} from '$app/navigation'
  import {onDestroy, onMount} from 'svelte'
  import {client} from './client'

  let subscription: ReturnType<ReturnType<typeof client.live.events>['subscribe']> | null = null

  onMount(() => {
    subscription = client.live.events().subscribe({
      next: (event) => {
        const url = new URL(window.location.href)

        if (event.type === 'welcome') {
          console.info('Sanity is live with automatic revalidation of published content')
          if (!url.searchParams.has('lastLiveEventId')) {
            url.searchParams.set(
              'lastLiveEventId',
              // @ts-expect-error - @TODO upgrade `@sanity/client` with the id of welcome events
              event.id,
            )
            // eslint-disable-next-line svelte/no-navigation-without-resolve
            goto(url.toString(), {replaceState: true})
          }
        } else if (event.type === 'message') {
          // @TODO add tags matching here, somehow
          // Check if the event tags intersect with our component tags
          // if (event.tags?.some((tag) => tags.includes(tag))) {
          url.searchParams.set('lastLiveEventId', event.id)
          // eslint-disable-next-line svelte/no-navigation-without-resolve
          goto(url.toString(), {replaceState: true})
          // }
        } else if (event.type === 'restart' || event.type === 'reconnect') {
          url.searchParams.delete('lastLiveEventId')
          // eslint-disable-next-line svelte/no-navigation-without-resolve
          goto(url.toString(), {replaceState: true})
        }
      },
      error: (error) => {
        if (error instanceof CorsOriginError) {
          console.warn(
            `Sanity Live is unable to connect to the Sanity API as the current origin - ${window.origin} - is not in the list of allowed CORS origins for this Sanity Project.`,
            error.addOriginUrl && `Add it here:`,
            error.addOriginUrl?.toString(),
          )
        } else {
          console.error(error)
        }
      },
    })
  })

  onDestroy(() => {
    if (subscription) {
      subscription.unsubscribe()
    }
  })
</script>
