// sveltekit/src/lib/sanity/ThemeButton.svelte
<script lang="ts">
  let pending = $state(false)

  async function handleClick() {
    pending = true
    try {
      await fetch('https://lcapi-examples-api.sanity.dev/api/random-color-theme', {
        method: 'PUT',
      })
    } finally {
      pending = false
    }
  }
</script>

<button
  disabled={pending}
  onclick={handleClick}
  class="bg-(--theme-text) text-(--theme-background) focus:ring-(--theme-text) focus:ring-offset-(--theme-background) focus:outline-hidden cursor-pointer select-none rounded-md px-4 py-2 text-sm font-semibold transition ease-in-out focus:ring-2 focus:ring-offset-2 focus:duration-0 disabled:cursor-not-allowed disabled:opacity-50 {pending
    ? 'animate-pulse cursor-wait duration-150'
    : 'duration-1000'}"
>
  {pending ? 'Generating...' : 'Random Color Theme'}
</button>

// next-14/src/components/ThemeButton.tsx
import {useState} from 'react'

export default function ThemeButton() {
  const [pending, setPending] = useState(false)

  return (
    <button
      disabled={pending}
      onClick={() => {
        setPending(true)
        fetch('https://lcapi-examples-api.sanity.dev/api/random-color-theme', {
          method: 'PUT',
        }).finally(() => setPending(false))
      }}
      className={`bg-theme-button text-theme-button focus:ring-theme focus:ring-opacity-50 focus:ring-offset-theme cursor-pointer rounded-md px-4 py-2 text-sm font-semibold transition ease-in-out select-none focus:ring-2 focus:ring-offset-2 focus:duration-0 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50 ${pending ? 'animate-pulse cursor-wait duration-150' : 'duration-1000'} `}
    >
      {pending ? 'Generating...' : 'Random Color Theme'}
    </button>
  )
}
